export type PdfSection = {
  heading: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type PdfMetaItem = { label: string; value: string };

export type PdfDocument = {
  title: string;
  subtitle: string;
  comparisonId?: string | null;
  generatedAt?: Date;
  /** Key-value pairs rendered as a summary row below the title rule (e.g. Fit Level, Confidence, Recommendation). */
  metadata?: PdfMetaItem[];
  /** Short note shown on the left side of the footer, e.g. "Confidential — Generated by PreMarket AI". */
  footerNote?: string;
  sections: PdfSection[];
};

export function asText(value: unknown) {
  return typeof value === 'string' ? value.trim() : '';
}

export function getComparisonId(req: any, comparisonIdParam?: string) {
  if (comparisonIdParam && comparisonIdParam.trim().length > 0) {
    return comparisonIdParam.trim();
  }

  const rawId = Array.isArray(req.query?.id) ? req.query.id[0] : req.query?.id;
  return String(rawId || '').trim();
}

export function slugify(value: string) {
  return (
    String(value || '')
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'document-comparison'
  );
}

function normalizePdfText(value: unknown) {
  return String(value || '')
    .replace(/\r/g, '')
    .replace(/\u2018|\u2019/g, "'")
    .replace(/\u201C|\u201D/g, '"')
    .replace(/\u2013/g, '-')
    .replace(/\u2014/g, '--')
    .replace(/\u2026/g, '...')
    .replace(/\u00A0/g, ' ')
    .replace(/\u2022/g, '-')
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, '')
    .trim();
}

function toSafeLines(value: unknown) {
  return normalizePdfText(value)
    .split(/\n+/g)
    .map((line) => line.trim())
    .filter(Boolean);
}

function normalizeBullet(value: unknown) {
  return normalizePdfText(value).replace(/^[-*+\d.() ]+/, '').trim();
}

export function toParagraphs(value: unknown) {
  return toSafeLines(value);
}

function formatGeneratedAt(value: Date) {
  return value.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export async function renderProfessionalPdfBuffer(document: PdfDocument) {
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const marginLeft = 52;
  const marginRight = 52;
  const marginTop = 56;
  const marginBottom = 56;
  const textWidth = pageWidth - marginLeft - marginRight;
  // Reserve 32pt for footer; pages 2+ get a 20pt running header at top.
  const contentBottom = pageHeight - marginBottom - 32;
  const runningHeaderReserve = 20;

  let y = marginTop;

  const ensureSpace = (requiredHeight: number) => {
    if (y + requiredHeight <= contentBottom) {
      return;
    }
    pdf.addPage();
    // Leave room for the running header rendered in the post-pass.
    y = marginTop + runningHeaderReserve;
  };

  const writeWrappedLine = ({
    text,
    fontSize = 11,
    bold = false,
    color = [15, 23, 42],
    indent = 0,
    lineHeight,
    gapAfter = 0,
  }: {
    text: string;
    fontSize?: number;
    bold?: boolean;
    color?: [number, number, number];
    indent?: number;
    lineHeight?: number;
    gapAfter?: number;
  }) => {
    const safeText = normalizePdfText(text);
    if (!safeText) {
      return;
    }

    const resolvedLineHeight = Number(lineHeight || Math.max(15, fontSize + 4));
    pdf.setFont('helvetica', bold ? 'bold' : 'normal');
    pdf.setTextColor(color[0], color[1], color[2]);
    pdf.setFontSize(fontSize);

    const maxWidth = Math.max(80, textWidth - indent);
    const lines = pdf.splitTextToSize(safeText, maxWidth);
    ensureSpace(lines.length * resolvedLineHeight + gapAfter + 2);

    lines.forEach((line: string) => {
      pdf.text(line, marginLeft + indent, y);
      y += resolvedLineHeight;
    });
    y += gapAfter;
  };

  const generatedAt = document.generatedAt || new Date();

  // ── Page 1 document header ──────────────────────────────────────────────────
  writeWrappedLine({
    text: document.title || 'Document Comparison',
    fontSize: 20,
    bold: true,
    lineHeight: 26,
    gapAfter: 6,
  });
  writeWrappedLine({
    text: document.subtitle || '',
    fontSize: 12,
    color: [71, 85, 105],
    gapAfter: 4,
  });
  writeWrappedLine({
    text: `Generated: ${formatGeneratedAt(generatedAt)}`,
    fontSize: 10,
    color: [100, 116, 139],
    gapAfter: 2,
  });
  if (asText(document.comparisonId)) {
    writeWrappedLine({
      text: `Comparison ID: ${asText(document.comparisonId)}`,
      fontSize: 10,
      color: [100, 116, 139],
      gapAfter: 10,
    });
  } else {
    y += 8;
  }

  // Title rule
  pdf.setDrawColor(203, 213, 225);
  pdf.setLineWidth(1);
  pdf.line(marginLeft, y, pageWidth - marginRight, y);
  y += 16;

  // ── Metadata summary row (Fit Level · Confidence · Recommendation) ──────────
  const metaItems = Array.isArray(document.metadata) ? document.metadata : [];
  if (metaItems.length > 0) {
    const metaLine = metaItems
      .map((m) => `${normalizePdfText(m.label)}: ${normalizePdfText(m.value)}`)
      .join('   ·   ');
    writeWrappedLine({
      text: metaLine,
      fontSize: 10,
      bold: false,
      color: [51, 65, 85],
      gapAfter: 12,
    });
    pdf.setDrawColor(226, 232, 240);
    pdf.setLineWidth(0.5);
    pdf.line(marginLeft, y, pageWidth - marginRight, y);
    y += 14;
  }

  // ── Sections ───────────────────────────────────────────────────────────────
  const sections = Array.isArray(document.sections) ? document.sections : [];
  sections.forEach((section, sectionIndex) => {
    if (sectionIndex > 0) {
      y += 10;
      // Thin inter-section divider
      pdf.setDrawColor(241, 245, 249);
      pdf.setLineWidth(0.5);
      pdf.line(marginLeft, y, pageWidth - marginRight, y);
      y += 10;
    }

    writeWrappedLine({
      text: section.heading || `Section ${sectionIndex + 1}`,
      fontSize: 13,
      bold: true,
      color: [30, 58, 138], // indigo-900
      lineHeight: 19,
      gapAfter: 6,
    });

    const paragraphs = Array.isArray(section.paragraphs) ? section.paragraphs : [];
    paragraphs.forEach((paragraph, paragraphIndex) => {
      writeWrappedLine({
        text: paragraph,
        fontSize: 11,
        lineHeight: 16,
        gapAfter: paragraphIndex === paragraphs.length - 1 ? 4 : 3,
      });
    });

    const bullets = Array.isArray(section.bullets) ? section.bullets : [];
    bullets.forEach((bullet, bulletIndex) => {
      const normalized = normalizeBullet(bullet);
      if (!normalized) {
        return;
      }
      writeWrappedLine({
        text: `• ${normalized}`,
        fontSize: 11,
        lineHeight: 16,
        indent: 6,
        gapAfter: bulletIndex === bullets.length - 1 ? 4 : 2,
      });
    });
  });

  // ── Post-pass: running headers (pages 2+) + footer ────────────────────────
  const totalPages = pdf.getNumberOfPages();
  const runningTitle = normalizePdfText(document.subtitle
    ? `${document.title || 'Document Comparison'}  —  ${document.subtitle}`
    : (document.title || 'Document Comparison'));
  const footerNote = normalizePdfText(document.footerNote || '');

  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    pdf.setPage(pageNumber);

    // Running header on pages 2+
    if (pageNumber > 1) {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8);
      pdf.setTextColor(148, 163, 184);
      pdf.text(runningTitle, marginLeft, marginTop - 10);
      pdf.setDrawColor(226, 232, 240);
      pdf.setLineWidth(0.5);
      pdf.line(marginLeft, marginTop - 4, pageWidth - marginRight, marginTop - 4);
    }

    // Footer
    const footerY = pageHeight - 20;
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(148, 163, 184);
    if (footerNote) {
      pdf.text(footerNote, marginLeft, footerY);
    }
    pdf.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - marginRight, footerY, {
      align: 'right',
    });
  }

  return Buffer.from(pdf.output('arraybuffer'));
}

export function sendPdf(res: any, filename: string, buffer: Buffer) {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Cache-Control', 'no-store');
  res.end(buffer);
}
