type MetadataShape = Record<string, unknown>;

const proposerMeta = (moduleKey: string, overrides: MetadataShape = {}): MetadataShape => ({
  party: 'a',
  applies_to_role: 'proposer',
  module_key: moduleKey,
  role_type: 'party_attribute',
  supports_visibility: true,
  ...overrides,
});

const recipientMeta = (moduleKey: string, overrides: MetadataShape = {}): MetadataShape => ({
  party: 'b',
  applies_to_role: 'recipient',
  module_key: moduleKey,
  role_type: 'counterparty_observation',
  is_about_counterparty: true,
  supports_visibility: false,
  ...overrides,
});

const sharedMeta = (moduleKey: string, overrides: MetadataShape = {}): MetadataShape => ({
  party: 'a',
  applies_to_role: 'both',
  module_key: moduleKey,
  role_type: 'shared_fact',
  supports_visibility: false,
  ...overrides,
});

const ENTERPRISE_PRESET_ALL = {
  vendor_prequal: true,
  saas_procurement: true,
  private_rfp_prequal: true,
  api_data_provider: true,
};

const ENTERPRISE_PRESET_VENDOR = { vendor_prequal: true };
const ENTERPRISE_PRESET_SAAS = { saas_procurement: true };
const ENTERPRISE_PRESET_RFP = { private_rfp_prequal: true };
const ENTERPRISE_PRESET_API = { api_data_provider: true };
const ENTERPRISE_PRESET_SAAS_AND_API = {
  saas_procurement: true,
  api_data_provider: true,
};

export const CANONICAL_TEMPLATE_DEFINITIONS = [
  {
    id: 'builtin:universal_enterprise_onboarding',
    slug: 'universal_enterprise_onboarding',
    templateKey: 'universal_enterprise_onboarding',
    category: 'saas_procurement',
    name: 'Universal Enterprise Onboarding',
    description:
      'Assess onboarding readiness across security, privacy, operations, and commercial requirements.',
    partyALabel: 'Proposer',
    partyBLabel: 'Recipient',
    status: 'active',
    sortOrder: 10,
    sections: [
      {
        key: 'org_profile',
        title: 'Organization Profile',
        sortOrder: 10,
        questions: [
          {
            key: 'org_type_self',
            label: 'Organization Type',
            description: 'What best describes your organization?',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 10,
            options: ['Startup', 'SMB', 'Mid-Market', 'Enterprise'],
            metadata: proposerMeta('org_profile', {
              supports_visibility: false,
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'org_size_self',
            label: 'Organization Size',
            description: 'Headcount or company size band.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 20,
            options: ['1-10', '11-50', '51-200', '201-1000', '1000+'],
            metadata: proposerMeta('org_profile', {
              supports_visibility: false,
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'industry_self',
            label: 'Primary Industry',
            description: 'Which industry best reflects your organization?',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 30,
            options: [
              'Financial Services',
              'Healthcare',
              'Retail / Commerce',
              'Technology',
              'Public Sector',
              'Other',
            ],
            metadata: proposerMeta('org_profile', {
              supports_visibility: false,
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'operating_regions_self',
            label: 'Operating Regions',
            description: 'Where do you currently operate?',
            fieldType: 'multi_select',
            valueType: 'text',
            required: true,
            sortOrder: 40,
            options: ['North America', 'Europe', 'APAC', 'LATAM', 'Middle East', 'Africa'],
            metadata: proposerMeta('org_profile', {
              supports_visibility: false,
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'website_self',
            label: 'Website',
            description: 'Primary website URL.',
            fieldType: 'url',
            valueType: 'text',
            required: true,
            sortOrder: 50,
            metadata: proposerMeta('org_profile', {
              supports_visibility: false,
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'org_type_counterparty',
            label: 'Required Counterparty Type',
            description: 'Preferred recipient organization profile.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 60,
            options: ['Startup', 'SMB', 'Mid-Market', 'Enterprise', 'No preference'],
            metadata: recipientMeta('org_profile', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'org_size_counterparty',
            label: 'Counterparty Size Preference',
            description: 'Preferred recipient company size.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 70,
            options: ['1-10', '11-50', '51-200', '201-1000', '1000+', 'No preference'],
            metadata: recipientMeta('org_profile', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'region_constraints_counterparty',
            label: 'Counterparty Region Requirements',
            description: 'Required regions for the recipient.',
            fieldType: 'multi_select',
            valueType: 'text',
            required: false,
            sortOrder: 80,
            options: ['North America', 'Europe', 'APAC', 'LATAM', 'Middle East', 'Africa'],
            metadata: recipientMeta('org_profile', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
        ],
      },
      {
        key: 'security_compliance',
        title: 'Security & Compliance',
        sortOrder: 20,
        questions: [
          {
            key: 'mfa_enforced_self',
            label: 'MFA Enforced',
            description: 'Is MFA enforced for privileged access?',
            fieldType: 'boolean',
            valueType: 'text',
            required: true,
            sortOrder: 100,
            metadata: proposerMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'sso_supported_self',
            label: 'SSO Supported',
            description: 'Do you support SSO/SAML for enterprise access?',
            fieldType: 'boolean',
            valueType: 'text',
            required: true,
            sortOrder: 110,
            metadata: proposerMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'encrypt_transit_self',
            label: 'Encryption In Transit',
            description: 'Is customer data encrypted in transit?',
            fieldType: 'boolean',
            valueType: 'text',
            required: true,
            sortOrder: 120,
            metadata: proposerMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'encrypt_rest_self',
            label: 'Encryption At Rest',
            description: 'Is customer data encrypted at rest?',
            fieldType: 'boolean',
            valueType: 'text',
            required: true,
            sortOrder: 130,
            metadata: proposerMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'soc2_status_self',
            label: 'SOC 2 Status',
            description: 'Most recent SOC 2 posture.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 140,
            options: ['Not started', 'In progress', 'Type I', 'Type II'],
            metadata: proposerMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'iso27001_self',
            label: 'ISO 27001 Status',
            description: 'Do you maintain ISO 27001 certification?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 150,
            options: ['No', 'In progress', 'Certified'],
            metadata: proposerMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'pentest_freq_self',
            label: 'Penetration Testing Frequency',
            description: 'How often is external penetration testing performed?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 160,
            options: ['Never', 'Annually', 'Semi-Annual', 'Quarterly'],
            metadata: proposerMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'trust_center_url_self',
            label: 'Trust Center URL',
            description: 'Link to your trust center or security overview.',
            fieldType: 'url',
            valueType: 'text',
            required: false,
            sortOrder: 170,
            metadata: proposerMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'min_soc2_counterparty',
            label: 'Minimum SOC 2 Requirement',
            description: 'Minimum acceptable counterparty posture.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 180,
            options: ['None', 'In progress', 'Type I', 'Type II'],
            metadata: recipientMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'require_sso_counterparty',
            label: 'Counterparty Must Support SSO',
            description: 'Whether SSO support is required from the counterparty.',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 190,
            metadata: recipientMeta('security_compliance', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
        ],
      },
      {
        key: 'privacy_data_handling',
        title: 'Privacy & Data Handling',
        sortOrder: 30,
        questions: [
          {
            key: 'data_types_self',
            label: 'Data Categories Handled',
            description: 'Select the customer data categories you handle.',
            fieldType: 'multi_select',
            valueType: 'text',
            required: true,
            sortOrder: 200,
            options: [
              'PII',
              'Financial Data',
              'Health Data',
              'Usage Analytics',
              'Operational Metadata',
              'No Sensitive Data',
            ],
            metadata: proposerMeta('privacy_data_handling', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'data_residency_self',
            label: 'Data Residency',
            description: 'Primary data residency model.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 210,
            options: ['US only', 'EU only', 'Regional options', 'Global'],
            metadata: proposerMeta('privacy_data_handling', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'retention_policy_self',
            label: 'Data Retention Policy',
            description: 'Describe your standard data retention approach.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 220,
            options: ['Configurable', 'Fixed by plan', 'By contract', 'Not documented'],
            metadata: proposerMeta('privacy_data_handling', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'dpa_available_self',
            label: 'DPA Available',
            description: 'Can you provide a standard DPA?',
            fieldType: 'boolean',
            valueType: 'text',
            required: true,
            sortOrder: 230,
            metadata: proposerMeta('privacy_data_handling', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'dpa_template_self',
            label: 'DPA Notes',
            description: 'Share notes about DPA coverage, subprocessors, and terms.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 240,
            metadata: proposerMeta('privacy_data_handling', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'data_residency_req_counterparty',
            label: 'Counterparty Residency Requirement',
            description: 'Required residency model from the recipient perspective.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 250,
            options: ['US only', 'EU only', 'Regional options', 'No preference'],
            metadata: recipientMeta('privacy_data_handling', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'dpa_required_counterparty',
            label: 'Counterparty DPA Requirement',
            description: 'Whether the recipient requires a signed DPA before go-live.',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 260,
            metadata: recipientMeta('privacy_data_handling', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
        ],
      },
      {
        key: 'operations_sla',
        title: 'Operations & Support',
        sortOrder: 40,
        questions: [
          {
            key: 'uptime_target_self',
            label: 'Uptime Target',
            description: 'Published uptime objective.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 300,
            options: ['99.0%', '99.5%', '99.9%', '99.95%', '99.99%'],
            metadata: proposerMeta('operations_sla', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'support_model_self',
            label: 'Support Model',
            description: 'Primary support model offered.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 310,
            options: ['Email only', 'Business hours', '24/5', '24/7', 'Dedicated TAM'],
            metadata: proposerMeta('operations_sla', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'incident_notification_self',
            label: 'Incident Notification SLA',
            description: 'How quickly do you notify customers after critical incidents?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 320,
            options: ['Within 1 hour', 'Within 4 hours', 'Within 24 hours', 'Best effort'],
            metadata: proposerMeta('operations_sla', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'min_uptime_counterparty',
            label: 'Minimum Counterparty Uptime',
            description: 'Minimum acceptable uptime for counterparty services.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 330,
            options: ['99.0%', '99.5%', '99.9%', '99.95%', '99.99%'],
            metadata: recipientMeta('operations_sla', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'required_support_counterparty',
            label: 'Counterparty Support Requirement',
            description: 'Expected support model from counterparty.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 340,
            options: ['Business hours', '24/5', '24/7', 'Dedicated TAM'],
            metadata: recipientMeta('operations_sla', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'required_incident_notify_counterparty',
            label: 'Counterparty Incident Notification Requirement',
            description: 'Maximum acceptable incident notification delay.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 350,
            options: ['Within 1 hour', 'Within 4 hours', 'Within 24 hours'],
            metadata: recipientMeta('operations_sla', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
        ],
      },
      {
        key: 'implementation_it',
        title: 'Implementation & IT',
        sortOrder: 50,
        questions: [
          {
            key: 'deployment_model_self',
            label: 'Deployment Model',
            description: 'How is your solution deployed?',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 400,
            options: ['Multi-tenant SaaS', 'Single-tenant SaaS', 'Private cloud', 'On-premises'],
            metadata: proposerMeta('implementation_it', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'integration_methods_self',
            label: 'Integration Methods',
            description: 'Available integration methods.',
            fieldType: 'multi_select',
            valueType: 'text',
            required: false,
            sortOrder: 410,
            options: ['REST API', 'GraphQL', 'SFTP', 'Webhook', 'Native connectors'],
            metadata: proposerMeta('implementation_it', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'onboarding_time_self',
            label: 'Typical Onboarding Time',
            description: 'Typical time to first production launch.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 420,
            options: ['< 2 weeks', '2-4 weeks', '1-2 months', '2-3 months', '3+ months'],
            metadata: proposerMeta('implementation_it', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'preferred_deployment_counterparty',
            label: 'Preferred Counterparty Deployment',
            description: 'Preferred deployment model from counterparty.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 430,
            options: ['Multi-tenant SaaS', 'Single-tenant SaaS', 'Private cloud', 'On-premises', 'Any'],
            metadata: recipientMeta('implementation_it', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'must_have_integrations_counterparty',
            label: 'Must-Have Counterparty Integrations',
            description: 'Critical integration requirements expected from the counterparty.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 440,
            metadata: recipientMeta('implementation_it', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'target_onboarding_counterparty',
            label: 'Counterparty Onboarding Timeline Requirement',
            description: 'Required implementation timeline from counterparty.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 450,
            options: ['< 2 weeks', '2-4 weeks', '1-2 months', '2-3 months', '3+ months'],
            metadata: recipientMeta('implementation_it', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
        ],
      },
      {
        key: 'legal_commercial',
        title: 'Legal & Commercial',
        sortOrder: 60,
        questions: [
          {
            key: 'pricing_model_self',
            label: 'Pricing Model',
            description: 'Describe your commercial model.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 500,
            options: ['Subscription', 'Usage-based', 'Hybrid', 'Enterprise contract'],
            metadata: proposerMeta('legal_commercial', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'contracting_readiness_self',
            label: 'Contracting Readiness',
            description: 'How prepared are your legal and procurement workflows?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 510,
            options: ['Standard terms ready', 'Negotiable with legal review', 'Case-by-case only'],
            metadata: proposerMeta('legal_commercial', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'insurance_available_self',
            label: 'Insurance Coverage Available',
            description: 'Do you maintain relevant liability coverage?',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 520,
            metadata: proposerMeta('legal_commercial', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'preferred_pricing_counterparty',
            label: 'Preferred Counterparty Pricing',
            description: 'Preferred pricing model from the recipient.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 530,
            options: ['Subscription', 'Usage-based', 'Hybrid', 'Any'],
            metadata: recipientMeta('legal_commercial', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'contract_requirement_counterparty',
            label: 'Counterparty Contract Requirements',
            description: 'Specific contract requirements expected from the counterparty.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 540,
            metadata: recipientMeta('legal_commercial', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'requires_insurance_counterparty',
            label: 'Counterparty Insurance Requirement',
            description: 'Whether counterparty proof of insurance is required.',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 550,
            metadata: recipientMeta('legal_commercial', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
        ],
      },
      {
        key: 'references',
        title: 'References & Proof',
        sortOrder: 70,
        questions: [
          {
            key: 'references_available_self',
            label: 'Reference Customers Available',
            description: 'Can you provide relevant customer references?',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 600,
            metadata: proposerMeta('references', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'case_studies_available_self',
            label: 'Case Studies Available',
            description: 'Can you share implementation case studies?',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 610,
            metadata: proposerMeta('references', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
          {
            key: 'will_require_refs_counterparty',
            label: 'Counterparty Requires References',
            description: 'Whether references are required by the recipient.',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 620,
            metadata: recipientMeta('references', {
              preset_visible: ENTERPRISE_PRESET_ALL,
            }),
          },
        ],
      },
      {
        key: 'vendor_specific',
        title: 'Vendor Screening',
        sortOrder: 80,
        questions: [
          {
            key: 'vendor_screening_priority_self',
            label: 'Vendor Screening Priority',
            description: 'What is the primary objective of this vendor pre-qualification?',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 700,
            options: ['Security risk', 'Cost efficiency', 'Operational fit', 'Procurement compliance'],
            metadata: proposerMeta('vendor_specific', {
              preset_visible: ENTERPRISE_PRESET_VENDOR,
            }),
          },
          {
            key: 'vendor_risk_tier_counterparty',
            label: 'Counterparty Risk Tier Requirement',
            description: 'Required vendor risk tier expected by the recipient.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 710,
            options: ['Low', 'Medium', 'High', 'Critical'],
            metadata: recipientMeta('vendor_specific', {
              preset_visible: ENTERPRISE_PRESET_VENDOR,
            }),
          },
        ],
      },
      {
        key: 'saas_specific',
        title: 'SaaS Procurement',
        sortOrder: 90,
        questions: [
          {
            key: 'saas_contract_term_self',
            label: 'Preferred Contract Term',
            description: 'Preferred standard commercial term length.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 800,
            options: ['Monthly', 'Annual', 'Multi-year'],
            metadata: proposerMeta('saas_specific', {
              preset_visible: ENTERPRISE_PRESET_SAAS_AND_API,
            }),
          },
          {
            key: 'saas_data_processor_addendum_counterparty',
            label: 'Counterparty DPA Addendum Requirement',
            description: 'Whether a DPA addendum is mandatory at procurement.',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 810,
            metadata: recipientMeta('saas_specific', {
              preset_visible: ENTERPRISE_PRESET_SAAS_AND_API,
            }),
          },
        ],
      },
      {
        key: 'rfp_specific',
        title: 'Private RFP Requirements',
        sortOrder: 100,
        questions: [
          {
            key: 'rfp_submission_timeline_self',
            label: 'RFP Submission Timeline',
            description: 'Expected timeline to submit full RFP response.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 900,
            options: ['< 1 week', '1-2 weeks', '2-4 weeks', '4+ weeks'],
            metadata: proposerMeta('rfp_specific', {
              preset_visible: ENTERPRISE_PRESET_RFP,
            }),
          },
          {
            key: 'rfp_mandatory_requirements_counterparty',
            label: 'Mandatory Counterparty RFP Requirements',
            description: 'Critical requirements the counterparty must satisfy in the RFP.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 910,
            metadata: recipientMeta('rfp_specific', {
              preset_visible: ENTERPRISE_PRESET_RFP,
            }),
          },
        ],
      },
      {
        key: 'api_data',
        title: 'API & Data Provider Matching',
        sortOrder: 110,
        questions: [
          {
            key: 'data_categories_self',
            label: 'Provided Data Categories',
            description: 'What data categories are available through your platform?',
            fieldType: 'multi_select',
            valueType: 'text',
            required: false,
            sortOrder: 1000,
            options: ['Company data', 'Financial data', 'Market data', 'Behavioral data', 'Regulatory data'],
            metadata: proposerMeta('api_data', {
              preset_required: { api_data_provider: true },
              preset_visible: ENTERPRISE_PRESET_API,
            }),
          },
          {
            key: 'update_frequency_self',
            label: 'Data Update Frequency',
            description: 'How frequently is the source data refreshed?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 1010,
            options: ['Real-time', 'Hourly', 'Daily', 'Weekly', 'Monthly'],
            metadata: proposerMeta('api_data', {
              preset_required: { api_data_provider: true },
              preset_visible: ENTERPRISE_PRESET_API,
            }),
          },
          {
            key: 'delivery_method_self',
            label: 'Delivery Methods',
            description: 'Supported delivery methods for shared data.',
            fieldType: 'multi_select',
            valueType: 'text',
            required: false,
            sortOrder: 1020,
            options: ['REST API', 'Webhook', 'SFTP', 'Bulk export'],
            metadata: proposerMeta('api_data', {
              preset_visible: ENTERPRISE_PRESET_API,
            }),
          },
          {
            key: 'licensing_clarity_self',
            label: 'Licensing Clarity',
            description: 'How clearly are usage rights and licensing constraints documented?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 1030,
            options: ['Clear license', 'Some restrictions', 'Unclear/Negotiable'],
            metadata: proposerMeta('api_data', {
              preset_visible: ENTERPRISE_PRESET_API,
            }),
          },
          {
            key: 'required_data_categories_counterparty',
            label: 'Required Data Categories',
            description: 'Critical data categories expected by the recipient.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 1040,
            metadata: recipientMeta('api_data', {
              preset_visible: ENTERPRISE_PRESET_API,
            }),
          },
          {
            key: 'min_update_frequency_counterparty',
            label: 'Minimum Required Update Frequency',
            description: 'Minimum acceptable refresh cadence expected by recipient.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 1050,
            options: ['Real-time', 'Hourly', 'Daily', 'Weekly', 'Monthly'],
            metadata: recipientMeta('api_data', {
              preset_visible: ENTERPRISE_PRESET_API,
            }),
          },
          {
            key: 'required_delivery_methods_counterparty',
            label: 'Required Delivery Methods',
            description: 'Required data delivery methods from recipient perspective.',
            fieldType: 'multi_select',
            valueType: 'text',
            required: false,
            sortOrder: 1060,
            options: ['REST API', 'Webhook', 'SFTP', 'Bulk export'],
            metadata: recipientMeta('api_data', {
              preset_visible: ENTERPRISE_PRESET_API,
            }),
          },
        ],
      },
    ],
  },
  {
    id: 'builtin:universal_finance_deal_prequal',
    slug: 'universal_finance_deal_prequal',
    templateKey: 'universal_finance_deal_prequal',
    category: 'investment',
    name: 'Universal Finance Deal Pre-Qual',
    description: 'Evaluate deal fit across investor criteria, M&A diligence, and lending requirements.',
    partyALabel: 'Proposer',
    partyBLabel: 'Party B (Recipient)',
    status: 'active',
    sortOrder: 20,
    sections: [
      {
        key: 'mode_selector',
        title: 'Deal Mode',
        sortOrder: 10,
        questions: [
          {
            key: 'mode',
            label: 'Deal Mode',
            description: 'Select the deal mode for this proposal.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 10,
            options: ['Investor Fit', 'M&A Fit', 'Lending Fit'],
            metadata: sharedMeta('mode_selector'),
          },
        ],
      },
      {
        key: 'common_core',
        title: 'Common Core',
        sortOrder: 20,
        questions: [
          {
            key: 'deal_stage_self',
            label: 'Deal Stage',
            description: 'Current stage of the opportunity.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 20,
            options: ['Sourcing', 'Diligence', 'Negotiation', 'Closing'],
            metadata: proposerMeta('common_core'),
          },
          {
            key: 'check_size_self',
            label: 'Target Check Size',
            description: 'Typical check or deal size.',
            fieldType: 'text',
            valueType: 'text',
            required: true,
            sortOrder: 30,
            metadata: proposerMeta('common_core'),
          },
          {
            key: 'transaction_size_band_self',
            label: 'Transaction Size Band',
            description: 'Estimated transaction size range.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 40,
            options: ['<$1M', '$1M-$10M', '$10M-$50M', '$50M-$250M', '$250M+'],
            metadata: proposerMeta('common_core'),
          },
          {
            key: 'geography_focus_self',
            label: 'Geography Focus',
            description: 'Primary regions for this deal.',
            fieldType: 'multi_select',
            valueType: 'text',
            required: false,
            sortOrder: 50,
            options: ['North America', 'Europe', 'APAC', 'LATAM', 'Middle East', 'Africa'],
            metadata: proposerMeta('common_core'),
          },
          {
            key: 'deal_timeline_self',
            label: 'Expected Close Timeline',
            description: 'When do you expect the deal to close?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 60,
            options: ['< 30 days', '30-60 days', '60-90 days', '90-180 days', '180+ days'],
            metadata: proposerMeta('common_core'),
          },
          {
            key: 'primary_use_of_funds_self',
            label: 'Primary Use of Funds',
            description: 'What is the primary use of proceeds?',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 70,
            metadata: proposerMeta('common_core'),
          },
          {
            key: 'preferred_check_size_counterparty',
            label: 'Counterparty Size Requirement',
            description: 'Preferred size expectation for the recipient.',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 80,
            metadata: recipientMeta('common_core'),
          },
          {
            key: 'preferred_geography_counterparty',
            label: 'Counterparty Geography Requirement',
            description: 'Required geographies for recipient fit.',
            fieldType: 'multi_select',
            valueType: 'text',
            required: false,
            sortOrder: 90,
            options: ['North America', 'Europe', 'APAC', 'LATAM', 'Middle East', 'Africa'],
            metadata: recipientMeta('common_core'),
          },
        ],
      },
      {
        key: 'investor_fit',
        title: 'Investor Fit',
        sortOrder: 30,
        questions: [
          {
            key: 'investor_thesis_self',
            label: 'Investor Thesis',
            description: 'What investment thesis drives interest?',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 100,
            metadata: proposerMeta('investor_fit', {
              preset_required: { investor_fit: true },
            }),
          },
          {
            key: 'target_return_self',
            label: 'Target Return Profile',
            description: 'What return profile are you targeting?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 110,
            options: ['Capital preservation', 'Income', 'Balanced growth', 'High growth'],
            metadata: proposerMeta('investor_fit', {
              preset_required: { investor_fit: true },
            }),
          },
          {
            key: 'exit_horizon_self',
            label: 'Exit Horizon',
            description: 'Target investment horizon before exit.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 120,
            options: ['< 2 years', '2-4 years', '4-7 years', '7+ years'],
            metadata: proposerMeta('investor_fit', {
              preset_required: { investor_fit: true },
            }),
          },
          {
            key: 'target_sector_counterparty',
            label: 'Target Sector Requirement',
            description: 'What sector focus does the recipient require?',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 130,
            metadata: recipientMeta('investor_fit', {
              preset_required: { investor_fit: true },
            }),
          },
          {
            key: 'preferred_stage_counterparty',
            label: 'Preferred Stage Requirement',
            description: 'Preferred company stage for recipient mandate.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 140,
            options: ['Seed', 'Series A', 'Series B', 'Growth', 'Late stage'],
            metadata: recipientMeta('investor_fit', {
              preset_required: { investor_fit: true },
            }),
          },
        ],
      },
      {
        key: 'm_and_a_fit',
        title: 'M&A Fit',
        sortOrder: 40,
        questions: [
          {
            key: 'acquisition_strategy_self',
            label: 'Acquisition Strategy',
            description: 'Strategic rationale for acquisition.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 150,
            metadata: proposerMeta('m_and_a_fit', {
              preset_required: { m_and_a_fit: true },
            }),
          },
          {
            key: 'synergy_model_self',
            label: 'Synergy Model',
            description: 'Expected cost/revenue synergies from the deal.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 160,
            metadata: proposerMeta('m_and_a_fit', {
              preset_required: { m_and_a_fit: true },
            }),
          },
          {
            key: 'integration_plan_self',
            label: 'Integration Plan Readiness',
            description: 'How ready is your post-close integration plan?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 170,
            options: ['Not started', 'Drafted', 'In progress', 'Finalized'],
            metadata: proposerMeta('m_and_a_fit', {
              preset_required: { m_and_a_fit: true },
            }),
          },
          {
            key: 'target_revenue_counterparty',
            label: 'Target Revenue Requirement',
            description: 'Revenue profile required by recipient.',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 180,
            metadata: recipientMeta('m_and_a_fit', {
              preset_required: { m_and_a_fit: true },
            }),
          },
          {
            key: 'required_transition_support_counterparty',
            label: 'Required Transition Support',
            description: 'Transition support expected by the recipient post-close.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 190,
            options: ['< 30 days', '30-90 days', '90-180 days', '180+ days'],
            metadata: recipientMeta('m_and_a_fit', {
              preset_required: { m_and_a_fit: true },
            }),
          },
        ],
      },
      {
        key: 'lending_fit',
        title: 'Lending Fit',
        sortOrder: 50,
        questions: [
          {
            key: 'collateral_available_self',
            label: 'Collateral Available',
            description: 'Can you provide qualifying collateral?',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 200,
            metadata: proposerMeta('lending_fit', {
              preset_required: { lending_fit: true },
            }),
          },
          {
            key: 'debt_service_coverage_self',
            label: 'Debt Service Coverage Ratio',
            description: 'Current or projected DSCR for the facility.',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 210,
            metadata: proposerMeta('lending_fit', {
              preset_required: { lending_fit: true },
            }),
          },
          {
            key: 'cash_runway_self',
            label: 'Cash Runway',
            description: 'Estimated cash runway under current plan.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 220,
            options: ['< 3 months', '3-6 months', '6-12 months', '12+ months'],
            metadata: proposerMeta('lending_fit', {
              preset_required: { lending_fit: true },
            }),
          },
          {
            key: 'minimum_interest_rate_counterparty',
            label: 'Maximum Interest Requirement',
            description: 'Recipient rate expectation or ceiling.',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 230,
            metadata: recipientMeta('lending_fit', {
              preset_required: { lending_fit: true },
            }),
          },
          {
            key: 'required_collateral_type_counterparty',
            label: 'Required Collateral Types',
            description: 'Collateral forms accepted by recipient.',
            fieldType: 'multi_select',
            valueType: 'text',
            required: false,
            sortOrder: 240,
            options: ['Accounts receivable', 'Inventory', 'Equipment', 'Property', 'Personal guarantee'],
            metadata: recipientMeta('lending_fit', {
              preset_required: { lending_fit: true },
            }),
          },
        ],
      },
    ],
  },
  {
    id: 'builtin:universal_profile_matching',
    slug: 'universal_profile_matching',
    templateKey: 'universal_profile_matching',
    category: 'beta_access',
    name: 'Universal Profile Matching',
    description:
      'Match profiles against requirements across jobs, beta access, programs, and grants.',
    partyALabel: 'Profile Owner',
    partyBLabel: 'Requirements Owner',
    status: 'active',
    sortOrder: 30,
    sections: [
      {
        key: 'mode_selector',
        title: 'Matching Mode',
        sortOrder: 10,
        questions: [
          {
            key: 'mode',
            label: 'Profile Matching Mode',
            description: 'Select the matching mode for this evaluation.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 10,
            options: ['Job Fit', 'Beta Access Fit', 'Program/Accelerator Fit', 'Grant/Scholarship Fit'],
            metadata: sharedMeta('mode_selector'),
          },
        ],
      },
      {
        key: 'shared_core',
        title: 'Shared Core',
        sortOrder: 20,
        questions: [
          {
            key: 'profile_headline_self',
            label: 'Profile Summary',
            description: 'Concise summary of your profile.',
            fieldType: 'textarea',
            valueType: 'text',
            required: true,
            sortOrder: 20,
            metadata: proposerMeta('shared_core'),
          },
          {
            key: 'experience_years_self',
            label: 'Experience Level',
            description: 'Years of relevant experience.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 30,
            options: ['0-2 years', '3-5 years', '6-10 years', '10+ years'],
            metadata: proposerMeta('shared_core'),
          },
          {
            key: 'strengths_self',
            label: 'Core Strengths',
            description: 'Top strengths relevant to this match.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 40,
            metadata: proposerMeta('shared_core'),
          },
          {
            key: 'availability_self',
            label: 'Availability',
            description: 'When are you available to start or participate?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 50,
            options: ['Immediate', 'Within 2 weeks', 'Within 1 month', '1+ month'],
            metadata: proposerMeta('shared_core'),
          },
          {
            key: 'portfolio_url_self',
            label: 'Portfolio / Profile URL',
            description: 'Optional link to portfolio or profile.',
            fieldType: 'url',
            valueType: 'text',
            required: false,
            sortOrder: 60,
            metadata: proposerMeta('shared_core'),
          },
          {
            key: 'requirements_summary_counterparty',
            label: 'Requirements Summary',
            description: 'High-level requirements from recipient.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 70,
            metadata: recipientMeta('shared_core'),
          },
          {
            key: 'preferred_experience_counterparty',
            label: 'Preferred Experience Level',
            description: 'Desired experience level from recipient perspective.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 80,
            options: ['0-2 years', '3-5 years', '6-10 years', '10+ years'],
            metadata: recipientMeta('shared_core'),
          },
        ],
      },
      {
        key: 'job_fit',
        title: 'Job Fit',
        sortOrder: 30,
        questions: [
          {
            key: 'skills_self',
            label: 'Core Skills',
            description: 'List your strongest skills.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 90,
            metadata: proposerMeta('job_fit', {
              preset_required: { job_fit: true },
            }),
          },
          {
            key: 'role_preferences_self',
            label: 'Role Preferences',
            description: 'Preferred role scope and responsibilities.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 100,
            metadata: proposerMeta('job_fit', {
              preset_required: { job_fit: true },
            }),
          },
          {
            key: 'compensation_expectations_self',
            label: 'Compensation Expectations',
            description: 'Expected compensation range or structure.',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 110,
            metadata: proposerMeta('job_fit', {
              preset_required: { job_fit: true },
            }),
          },
          {
            key: 'required_skills_counterparty',
            label: 'Required Skills',
            description: 'Recipient-required skills.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 120,
            metadata: recipientMeta('job_fit', {
              preset_required: { job_fit: true },
            }),
          },
          {
            key: 'work_model_counterparty',
            label: 'Work Model Requirement',
            description: 'Preferred work model for this role.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 130,
            options: ['Remote', 'Hybrid', 'On-site', 'Flexible'],
            metadata: recipientMeta('job_fit', {
              preset_required: { job_fit: true },
            }),
          },
        ],
      },
      {
        key: 'beta_access_fit',
        title: 'Beta Access Fit',
        sortOrder: 40,
        questions: [
          {
            key: 'product_focus_self',
            label: 'Product Focus',
            description: 'What product or domain do you focus on?',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 140,
            metadata: proposerMeta('beta_access_fit', {
              preset_required: { beta_access_fit: true },
            }),
          },
          {
            key: 'testing_capacity_self',
            label: 'Testing Capacity',
            description: 'How many hours per week can you dedicate to testing?',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 150,
            options: ['< 2 hours', '2-5 hours', '5-10 hours', '10+ hours'],
            metadata: proposerMeta('beta_access_fit', {
              preset_required: { beta_access_fit: true },
            }),
          },
          {
            key: 'feedback_workflow_self',
            label: 'Feedback Workflow',
            description: 'How do you provide structured product feedback?',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 160,
            metadata: proposerMeta('beta_access_fit', {
              preset_required: { beta_access_fit: true },
            }),
          },
          {
            key: 'ideal_tester_profile_counterparty',
            label: 'Ideal Tester Profile',
            description: 'Recipient description of ideal tester/user profile.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 170,
            metadata: recipientMeta('beta_access_fit', {
              preset_required: { beta_access_fit: true },
            }),
          },
          {
            key: 'required_testing_window_counterparty',
            label: 'Required Testing Window',
            description: 'Expected timeline for feedback cycles.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 180,
            options: ['1 week', '2 weeks', '1 month', 'Ongoing'],
            metadata: recipientMeta('beta_access_fit', {
              preset_required: { beta_access_fit: true },
            }),
          },
        ],
      },
      {
        key: 'program_fit',
        title: 'Program/Accelerator Fit',
        sortOrder: 50,
        questions: [
          {
            key: 'founder_background_self',
            label: 'Founder/Operator Background',
            description: 'Relevant background and accomplishments.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 190,
            metadata: proposerMeta('program_fit', {
              preset_required: { program_fit: true },
            }),
          },
          {
            key: 'traction_metrics_self',
            label: 'Traction Metrics',
            description: 'Current traction indicators (users, revenue, growth).',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 200,
            metadata: proposerMeta('program_fit', {
              preset_required: { program_fit: true },
            }),
          },
          {
            key: 'program_goals_self',
            label: 'Program Goals',
            description: 'What outcomes are you seeking from the program?',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 210,
            metadata: proposerMeta('program_fit', {
              preset_required: { program_fit: true },
            }),
          },
          {
            key: 'program_stage_counterparty',
            label: 'Program Stage Requirement',
            description: 'Required stage for admitted profiles.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 220,
            options: ['Idea', 'MVP', 'Growth', 'Scale'],
            metadata: recipientMeta('program_fit', {
              preset_required: { program_fit: true },
            }),
          },
          {
            key: 'required_commitment_counterparty',
            label: 'Required Commitment Level',
            description: 'Expected participation commitment from accepted candidates.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 230,
            options: ['Part-time', 'Full-time', 'Weekly milestones', 'Demo-day only'],
            metadata: recipientMeta('program_fit', {
              preset_required: { program_fit: true },
            }),
          },
        ],
      },
      {
        key: 'grant_fit',
        title: 'Grant/Scholarship Fit',
        sortOrder: 60,
        questions: [
          {
            key: 'impact_statement_self',
            label: 'Impact Statement',
            description: 'Describe expected impact and outcomes.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 240,
            metadata: proposerMeta('grant_fit', {
              preset_required: { grant_fit: true },
            }),
          },
          {
            key: 'outcomes_metrics_self',
            label: 'Outcome Metrics',
            description: 'How will impact be measured and reported?',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 250,
            metadata: proposerMeta('grant_fit', {
              preset_required: { grant_fit: true },
            }),
          },
          {
            key: 'funding_use_plan_self',
            label: 'Funding Use Plan',
            description: 'Planned use of grant or scholarship funds.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 260,
            metadata: proposerMeta('grant_fit', {
              preset_required: { grant_fit: true },
            }),
          },
          {
            key: 'eligibility_requirements_counterparty',
            label: 'Eligibility Requirements',
            description: 'Recipient eligibility and evidence requirements.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 270,
            metadata: recipientMeta('grant_fit', {
              preset_required: { grant_fit: true },
            }),
          },
          {
            key: 'reporting_frequency_counterparty',
            label: 'Reporting Frequency Requirement',
            description: 'Expected reporting cadence for awarded profiles.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 280,
            options: ['Monthly', 'Quarterly', 'Bi-annual', 'Annual'],
            metadata: recipientMeta('grant_fit', {
              preset_required: { grant_fit: true },
            }),
          },
        ],
      },
    ],
  },
];

export const DEFAULT_TEMPLATE_DEFINITIONS = CANONICAL_TEMPLATE_DEFINITIONS;

export function getDefaultTemplateById(templateId: string) {
  const normalized = String(templateId || '').trim().toLowerCase();
  if (!normalized) {
    return null;
  }

  return (
    CANONICAL_TEMPLATE_DEFINITIONS.find((definition) => {
      return definition.id.toLowerCase() === normalized || definition.slug.toLowerCase() === normalized;
    }) || null
  );
}
