export const CANONICAL_TEMPLATE_DEFINITIONS = [
  {
    id: 'builtin:universal_enterprise_onboarding',
    slug: 'universal_enterprise_onboarding',
    templateKey: 'universal_enterprise_onboarding',
    category: 'saas_procurement',
    name: 'Universal Enterprise Onboarding',
    description:
      'Assess onboarding readiness across security, privacy, operations, and commercial requirements.',
    partyALabel: 'Proposer',
    partyBLabel: 'Recipient',
    status: 'active',
    sortOrder: 10,
    sections: [
      {
        key: 'org_profile',
        title: 'Organization Profile',
        sortOrder: 10,
        questions: [
          {
            key: 'org_type_self',
            label: 'Organization Type',
            description: 'What best describes your organization?',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 10,
            options: ['Startup', 'SMB', 'Mid-Market', 'Enterprise'],
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'org_profile',
              role_type: 'party_attribute',
              supports_visibility: false,
            },
          },
          {
            key: 'org_size_self',
            label: 'Organization Size',
            description: 'Headcount or company size band.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 20,
            options: ['1-10', '11-50', '51-200', '201-1000', '1000+'],
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'org_profile',
              role_type: 'party_attribute',
              supports_visibility: false,
            },
          },
          {
            key: 'website_self',
            label: 'Website',
            description: 'Primary website URL.',
            fieldType: 'url',
            valueType: 'text',
            required: true,
            sortOrder: 30,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'org_profile',
              role_type: 'party_attribute',
              supports_visibility: false,
            },
          },
          {
            key: 'org_type_counterparty',
            label: 'Required Counterparty Type',
            description: 'Preferred recipient organization profile.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 40,
            options: ['Startup', 'SMB', 'Mid-Market', 'Enterprise', 'No preference'],
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'org_profile',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
            },
          },
        ],
      },
      {
        key: 'security_compliance',
        title: 'Security & Compliance',
        sortOrder: 20,
        questions: [
          {
            key: 'mfa_enforced_self',
            label: 'MFA Enforced',
            description: 'Is MFA enforced for privileged access?',
            fieldType: 'boolean',
            valueType: 'text',
            required: true,
            sortOrder: 50,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'security_compliance',
              role_type: 'party_attribute',
              supports_visibility: true,
            },
          },
          {
            key: 'soc2_status_self',
            label: 'SOC 2 Status',
            description: 'Most recent SOC 2 posture.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 60,
            options: ['Not started', 'In progress', 'Type I', 'Type II'],
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'security_compliance',
              role_type: 'party_attribute',
              supports_visibility: true,
            },
          },
          {
            key: 'min_soc2_counterparty',
            label: 'Minimum SOC 2 Requirement',
            description: 'Minimum acceptable counterparty posture.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 70,
            options: ['None', 'In progress', 'Type I', 'Type II'],
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'security_compliance',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
            },
          },
        ],
      },
      {
        key: 'legal_commercial',
        title: 'Legal & Commercial',
        sortOrder: 30,
        questions: [
          {
            key: 'pricing_model_self',
            label: 'Pricing Model',
            description: 'Describe your commercial model.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 80,
            options: ['Subscription', 'Usage-based', 'Hybrid', 'Enterprise contract'],
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'legal_commercial',
              role_type: 'party_attribute',
              supports_visibility: true,
            },
          },
          {
            key: 'preferred_pricing_counterparty',
            label: 'Preferred Counterparty Pricing',
            description: 'Preferred pricing model from the recipient.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 90,
            options: ['Subscription', 'Usage-based', 'Hybrid', 'Any'],
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'legal_commercial',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'builtin:universal_finance_deal_prequal',
    slug: 'universal_finance_deal_prequal',
    templateKey: 'universal_finance_deal_prequal',
    category: 'investment',
    name: 'Universal Finance Deal Pre-Qual',
    description: 'Evaluate deal fit across investor criteria, M&A diligence, and lending requirements.',
    partyALabel: 'Proposer',
    partyBLabel: 'Party B (Recipient)',
    status: 'active',
    sortOrder: 20,
    sections: [
      {
        key: 'mode_selector',
        title: 'Deal Mode',
        sortOrder: 10,
        questions: [
          {
            key: 'mode',
            label: 'Deal Mode',
            description: 'Select the deal mode for this proposal.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 10,
            options: ['Investor Fit', 'M&A Fit', 'Lending Fit'],
            metadata: {
              party: 'a',
              applies_to_role: 'both',
              module_key: 'mode_selector',
              role_type: 'shared_fact',
              supports_visibility: false,
            },
          },
        ],
      },
      {
        key: 'common_core',
        title: 'Common Core',
        sortOrder: 20,
        questions: [
          {
            key: 'deal_stage_self',
            label: 'Deal Stage',
            description: 'Current stage of the opportunity.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 20,
            options: ['Sourcing', 'Diligence', 'Negotiation', 'Closing'],
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'common_core',
              role_type: 'party_attribute',
              supports_visibility: true,
            },
          },
          {
            key: 'check_size_self',
            label: 'Target Check Size',
            description: 'Typical check or deal size.',
            fieldType: 'text',
            valueType: 'text',
            required: true,
            sortOrder: 30,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'common_core',
              role_type: 'party_attribute',
              supports_visibility: true,
            },
          },
          {
            key: 'preferred_check_size_counterparty',
            label: 'Counterparty Size Requirement',
            description: 'Preferred size expectation for the recipient.',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 40,
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'common_core',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
            },
          },
        ],
      },
      {
        key: 'investor_fit',
        title: 'Investor Fit',
        sortOrder: 30,
        questions: [
          {
            key: 'investor_thesis_self',
            label: 'Investor Thesis',
            description: 'What investment thesis drives interest?',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 50,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'investor_fit',
              role_type: 'party_attribute',
              supports_visibility: true,
              preset_required: { investor_fit: true },
            },
          },
          {
            key: 'target_sector_counterparty',
            label: 'Target Sector Requirement',
            description: 'What sector focus does the recipient require?',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 60,
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'investor_fit',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
              preset_required: { investor_fit: true },
            },
          },
        ],
      },
      {
        key: 'm_and_a_fit',
        title: 'M&A Fit',
        sortOrder: 40,
        questions: [
          {
            key: 'acquisition_strategy_self',
            label: 'Acquisition Strategy',
            description: 'Strategic rationale for acquisition.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 70,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'm_and_a_fit',
              role_type: 'party_attribute',
              supports_visibility: true,
              preset_required: { m_and_a_fit: true },
            },
          },
          {
            key: 'target_revenue_counterparty',
            label: 'Target Revenue Requirement',
            description: 'Revenue profile required by recipient.',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 80,
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'm_and_a_fit',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
              preset_required: { m_and_a_fit: true },
            },
          },
        ],
      },
      {
        key: 'lending_fit',
        title: 'Lending Fit',
        sortOrder: 50,
        questions: [
          {
            key: 'collateral_available_self',
            label: 'Collateral Available',
            description: 'Can you provide qualifying collateral?',
            fieldType: 'boolean',
            valueType: 'text',
            required: false,
            sortOrder: 90,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'lending_fit',
              role_type: 'party_attribute',
              supports_visibility: true,
              preset_required: { lending_fit: true },
            },
          },
          {
            key: 'minimum_interest_rate_counterparty',
            label: 'Maximum Interest Requirement',
            description: 'Recipient rate expectation or ceiling.',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 100,
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'lending_fit',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
              preset_required: { lending_fit: true },
            },
          },
        ],
      },
    ],
  },
  {
    id: 'builtin:universal_profile_matching',
    slug: 'universal_profile_matching',
    templateKey: 'universal_profile_matching',
    category: 'beta_access',
    name: 'Universal Profile Matching',
    description:
      'Match profiles against requirements across jobs, beta access, programs, and grants.',
    partyALabel: 'Profile Owner',
    partyBLabel: 'Requirements Owner',
    status: 'active',
    sortOrder: 30,
    sections: [
      {
        key: 'mode_selector',
        title: 'Matching Mode',
        sortOrder: 10,
        questions: [
          {
            key: 'mode',
            label: 'Profile Matching Mode',
            description: 'Select the matching mode for this evaluation.',
            fieldType: 'select',
            valueType: 'text',
            required: true,
            sortOrder: 10,
            options: ['Job Fit', 'Beta Access Fit', 'Program/Accelerator Fit', 'Grant/Scholarship Fit'],
            metadata: {
              party: 'a',
              applies_to_role: 'both',
              module_key: 'mode_selector',
              role_type: 'shared_fact',
              supports_visibility: false,
            },
          },
        ],
      },
      {
        key: 'shared_core',
        title: 'Shared Core',
        sortOrder: 20,
        questions: [
          {
            key: 'profile_headline_self',
            label: 'Profile Summary',
            description: 'Concise summary of your profile.',
            fieldType: 'textarea',
            valueType: 'text',
            required: true,
            sortOrder: 20,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'shared_core',
              role_type: 'party_attribute',
              supports_visibility: true,
            },
          },
          {
            key: 'requirements_summary_counterparty',
            label: 'Requirements Summary',
            description: 'High-level requirements from recipient.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 30,
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'shared_core',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
            },
          },
        ],
      },
      {
        key: 'job_fit',
        title: 'Job Fit',
        sortOrder: 30,
        questions: [
          {
            key: 'skills_self',
            label: 'Core Skills',
            description: 'List your strongest skills.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 40,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'job_fit',
              role_type: 'party_attribute',
              supports_visibility: true,
              preset_required: { job_fit: true },
            },
          },
          {
            key: 'required_skills_counterparty',
            label: 'Required Skills',
            description: 'Recipient-required skills.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 50,
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'job_fit',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
              preset_required: { job_fit: true },
            },
          },
        ],
      },
      {
        key: 'beta_access_fit',
        title: 'Beta Access Fit',
        sortOrder: 40,
        questions: [
          {
            key: 'product_focus_self',
            label: 'Product Focus',
            description: 'What product or domain do you focus on?',
            fieldType: 'text',
            valueType: 'text',
            required: false,
            sortOrder: 60,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'beta_access_fit',
              role_type: 'party_attribute',
              supports_visibility: true,
              preset_required: { beta_access_fit: true },
            },
          },
          {
            key: 'ideal_tester_profile_counterparty',
            label: 'Ideal Tester Profile',
            description: 'Recipient description of ideal tester/user profile.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 70,
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'beta_access_fit',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
              preset_required: { beta_access_fit: true },
            },
          },
        ],
      },
      {
        key: 'program_fit',
        title: 'Program/Accelerator Fit',
        sortOrder: 50,
        questions: [
          {
            key: 'founder_background_self',
            label: 'Founder/Operator Background',
            description: 'Relevant background and accomplishments.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 80,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'program_fit',
              role_type: 'party_attribute',
              supports_visibility: true,
              preset_required: { program_fit: true },
            },
          },
          {
            key: 'program_stage_counterparty',
            label: 'Program Stage Requirement',
            description: 'Required stage for admitted profiles.',
            fieldType: 'select',
            valueType: 'text',
            required: false,
            sortOrder: 90,
            options: ['Idea', 'MVP', 'Growth', 'Scale'],
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'program_fit',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
              preset_required: { program_fit: true },
            },
          },
        ],
      },
      {
        key: 'grant_fit',
        title: 'Grant/Scholarship Fit',
        sortOrder: 60,
        questions: [
          {
            key: 'impact_statement_self',
            label: 'Impact Statement',
            description: 'Describe expected impact and outcomes.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 100,
            metadata: {
              party: 'a',
              applies_to_role: 'proposer',
              module_key: 'grant_fit',
              role_type: 'party_attribute',
              supports_visibility: true,
              preset_required: { grant_fit: true },
            },
          },
          {
            key: 'eligibility_requirements_counterparty',
            label: 'Eligibility Requirements',
            description: 'Recipient eligibility and evidence requirements.',
            fieldType: 'textarea',
            valueType: 'text',
            required: false,
            sortOrder: 110,
            metadata: {
              party: 'b',
              applies_to_role: 'recipient',
              module_key: 'grant_fit',
              role_type: 'counterparty_observation',
              is_about_counterparty: true,
              supports_visibility: false,
              preset_required: { grant_fit: true },
            },
          },
        ],
      },
    ],
  },
];

export const DEFAULT_TEMPLATE_DEFINITIONS = CANONICAL_TEMPLATE_DEFINITIONS;

export function getDefaultTemplateById(templateId: string) {
  const normalized = String(templateId || '').trim().toLowerCase();
  if (!normalized) {
    return null;
  }

  return (
    CANONICAL_TEMPLATE_DEFINITIONS.find((definition) => {
      return definition.id.toLowerCase() === normalized || definition.slug.toLowerCase() === normalized;
    }) || null
  );
}
